name: ci


on:
  push:
    branches:
      - main
      - development

  pull_request:
    branches:
      - main 
      - development


jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Execute static analysis
        run: npm run typecheck

      - name: Execute linter
        run: npm run lint

      - name: Execute tests
        run: npm test
